### ISSUE TITLE
I hope it works

### ISSUE THREAD

**Issue by hudav** [ARSTCreations/phpshellscanner#1]
running against full datacenter
usa, au, rf
--auto-quarantine

**Comment by rizaldyaristyo** [comment]
oof, this project is now unfortunately simple and unstable. I advise to not use this for fixing integral systems or even production

might rework this project when i have the better knowledge

**Comment by hudav** [comment]
this tool was a master peace recovering a complete datacenter, as you said simple but effective it killed a lot of stuff false positives, but there was no escape for shells and backdoor sockets, the owners, billionaires were impossible to locate, and all support VOIP was taken down. can't comment where , when, who. thanks , you covered my back , (e)vil corp lost this time. 
kindly the sec team leave mour signature, b64_decode -> aHR0cDovL2Ftb3h0bGkuY29tLw
